### ISSUE TITLE
Improve detection of virtual environments for running glean_parser

### ISSUE THREAD

**Issue by alexgibson** [mozilla/glean.js#1219]
We're looking to test out Glean on [bedrock](https://github.com/mozilla/bedrock) and would like to install `glean_parser` as one of our regular Python dependencies, so that when Glean JS runs it will detect our virtual environment and use the already installed dependencies.

One of the issues we're running into is there seems to be an [assumption here](https://github.com/mozilla/glean.js/blob/eb9d0a5d5ade8d08ec1c1e2b76b879a9a113c80a/glean/src/cli.ts#L26) that the virtual environment folder is relative to the project root folder. On bedrock we're using [pyenv-virtualenv](https://github.com/pyenv/pyenv-virtualenv), so the directory can exist outside of the project structure.

It would be great if Glean could use the full path to a virtualenv's location when using the environment variable here, as opposed to assuming the end of the file path is what matters.

**Comment by stevejalim** [comment]
Hi - I work with Alex in MEAO. One quick/low-impact change that won't break current usage might be to expand this:

https://github.com/mozilla/glean.js/blob/eb9d0a5d5ade8d08ec1c1e2b76b879a9a113c80a/glean/src/cli.ts#L172

to use an env var that points to an absolure virtualenv path - eg `ISOLATED_VIRTUALENV_DIR` or similar (naming is hard 😆 ). I will take a swing at that now, locally, and see how it goes

**Comment by brizental** [comment]
> We're looking to test out Glean on [bedrock](https://github.com/mozilla/bedrock) and would like to install glean_parser as one of our regular Python dependencies, so that when Glean JS runs it will detect our virtual environment and use the already installed dependencies.

The one wrinkle with this is: how would you keep your dependency up to date with the glean_parser dependency on Glean.js? For this problem we already have [Bug 1742642](https://bugzilla.mozilla.org/show_bug.cgi?id=1742642), which is already in my "soon to do list", so it won't be a problem soon.

For the issue of passing a full path to the CLI for the virtualenv I have filed [Bug 1757148](https://bugzilla.mozilla.org/show_bug.cgi?id=1757148). I would be happy to reviews PRs if you have done the work already :) Otherwise I can take it soon too.

Thanks for flagging this :)

**Comment by alexgibson** [comment]
Thanks @brizental!

I don’t think this issue blocks us for running our evaluation, although I think @stevejalim might be working on a PR to allow passing the full path.

The dependency management bug you reference is a good catch, although not something I think we couldn’t manage manually in the short term.

**Comment by stevejalim** [comment]
@brizental Yep, I'm working on a PR towards the virtualenv path thing. Not sure if it'll match what you have in your head but once it's done, I will sent it your way and we can see if it's viable 😄

**Comment by brizental** [comment]
Closed by https://github.com/mozilla/glean.js/pull/1220
