### ISSUE TITLE
Improve glean/web compatibility for older browsers

### ISSUE THREAD

**Issue by alexgibson** [mozilla/glean.js#1393]
The bedrock team recently ran an in-production [evaluation](https://docs.google.com/presentation/d/1nA6v1iO8QEnyG-I9S2vaPfTTo87gqOgvd1jRqW-hd6Q/edit?usp=sharing) of Glean to see how it compared to Google Analytics. Whilst Glean showed favourable results on many product pages, on the main [Firefox download page](https://www.mozilla.org/firefox/new/), Glean saw a 17% decrease in page view pings, and a 12% decrease in Firefox desktop download click pings when compared to GA.

Looking at the data, I believe the largest attributable reason for this is because the main Firefox download page sees a high number of visits from users on older browsers where Glean is not currently supported. This is likely a mixture of people trying to set up new devices (using whatever browser came installed on their device in factory settings), and users referred from other websites to update their browser.

If we were to use Glean long term in production, a key requirement would likely be to try and improve backward compatibility for `glean/web` on older browsers. How this could be achieved is likely open to discussion, but several options could include:

- Transpile ES6 code to ES5 when publishing to NPM.
- Switch to, or fall back on older browser APIs when needed.
- Include a suggested list of polyfills required to support older browsers.

Polyfills seem like the lowest effort, however the downside of this would be a considerable increase in bundle size when Glean is already fairly large. Keeping Glean small should also be a secondary goal here.

**Comment by Dexterp37** [comment]
Filed this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1777185
