### ISSUE TITLE
Make glean/web pings faster

### ISSUE THREAD

**Issue by alexgibson** [mozilla/glean.js#1394]
The bedrock team recently ran an in-production [evaluation](https://docs.google.com/presentation/d/1nA6v1iO8QEnyG-I9S2vaPfTTo87gqOgvd1jRqW-hd6Q/edit?usp=sharing) of Glean to see how it compared to Google Analytics. One key finding was that we noticed a considerable drop in interaction pings compared to GA when people were clicking links from one web page to another. After some testing we discovered that pings were often not being constructed and/or sent in the time between someone clicking a link and the page unloading. 

We got around this in our test by introducing a small delay (of up to 1 second) for some of our main call-to-action clicks. After doing this we immediately saw interaction pings start to stabilise in comparison to GA. Obviously long term this isn't a great solution for us, as it starts to slow down our page navigations as well as complicates our click event handler code.

In terms of what we need as a website, we rarely need to store pings or queue them up (we already have max events set to 1). We simply need to fire a ping as fast as possible when our code says "go". It would be great if Glean could make the construction and transmission of pings for the web faster, and/or find a way to  try and ensure they are always sent before a page unloads.

I see that Glean uses the `keepalive` header when using `fetch`, but I wonder if some browser versions don't support that as well as others. I also wonder if the time it takes to actually create a ping and store it in the queue is also an issue.

**Comment by Dexterp37** [comment]
Filed this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1777182
