### ISSUE TITLE
Consider adding `config.storage?`

### ISSUE THREAD

**Issue by bakulf** [mozilla/glean.js#163]
In order to embed Glean.js easily in non-standard apps, I would like to have a `storage?: Storage` in the `ConfigurationInterface`, similarly to the new `httpClient?: Uploader`.

**Comment by brizental** [comment]
Hey @bakulf thank you for filing this. I have refiled this bug over on Bugzilla, which is our preferred bug tracker :)

https://bugzilla.mozilla.org/show_bug.cgi?id=1702419

Will follow up on the discussion over there.
