### ISSUE TITLE
Use globalThis instead of window?

### ISSUE THREAD

**Issue by Vinnl** [mozilla/glean.js#1789]
Unfortunately I haven't been able to exactly pin down what is going on yet, but [Glean 2.0.3](https://github.com/mozilla/glean.js/blob/main/CHANGELOG.md#v203-2023-09-27) broke Firefox Monitor (https://github.com/mozilla/blurts-server/pull/3595) in that it prevented other scripts from loading. It appears to have _something_ to do with assigning to `window` in an ES module, which possibly Next.js or Webpack doesn't like, maybe in combination with loading other scripts?

In any case, when I manually modify `/node_modules/@mozilla/glean/dist/core/glean/sync.js`, however, changing it to use [`globalThis`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) no longer blocked other scripts from loading, while keeping the global `Glean` object available:

```diff
- window.Glean = {
+ globalThis.Glean = {
     setLogPings: Glean.setLogPings,
      setDebugViewTag: Glean.setDebugViewTag,
      setSourceTags: Glean.setSourceTags
  };
``` 

So I was wondering if you'd consider making that change, or that I'll need to dive into this deeper?

**Comment by rosahbruno** [comment]
@Vinnl 
I put in a fix that now checks that `window` exists first before we set anything. We can definitely take some time to look into using `globalThis` instead, but for the short-term I am going to cut a new release v2.0.5 shortly that should fix our issues.

**Comment by Vinnl** [comment]
I'd swear that I had given that a try, but apparently not, because the new version works. Thanks!
