### ISSUE TITLE
glean.js should check for required WebExtension permissions

### ISSUE THREAD

**Issue by rhelmer** [mozilla/glean.js#569]
When the `storage` permission hasn't been requested by an extension, this somewhat cryptic exception is thrown:

```
Uncaught (in promise) TypeError: Cannot read property 'local' of undefined
    at new WebExtStore (storage.js:26)
    at new MetricsDatabase (database.js:38)
    at Function.initialize (glean.js:81)
    at Object.initialize (webext.js:6)
    at runStudy (study.js:74)
    at main.js:2
```

Would it make sense to [check for this at runtime](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions/contains)? I'd imagine that you could either make `initialize` check for everything it needs and fails, or check at the point of use... either way, it'd be super nice to have an exception like `"Missing required permission: storage"` or similar :)

**Comment by brizental** [comment]
Thanks for the bug report @rhelmer, this would be a good feature, I agree :) 

I have reposted this bug on Bugzilla which is our preferred bug tracker https://bugzilla.mozilla.org/show_bug.cgi?id=1723130
